ingestsql: lint: suppress error of unused return value of signal()
270 | static void on_signal(int sig) {
    |             ^
Error: /home/runner/work/cvmfs/cvmfs/cvmfs/swissknife_ingestsql.cc:271:3: error: the value returned by this function should not be disregarded; neglecting it may lead to errors [cert-err33-c,-warnings-as-errors]
271 |   signal(sig, SIG_DFL);
    |   ^~~~~~~~~~~~~~~~~~~~
/home/runner/work/cvmfs/cvmfs/cvmfs/swissknife_ingestsql.cc:271:3: note: cast the expression to void to silence this warning