Update googletest and fix building it on Archlinux
On Archlinux, building unit tests fails due to an ignored error of
googletest building.

* Make externals/googletest/*Hook.sh run with bash with `set -e` to
  so that failures are revealed.
* Update googletest version to the latest upstream release (tarball
  comes from official release on github).
* Drop cmake_compatibility.patch as it doesn't apply.

The problem looked as follows:

    $ make
    ...
    [ 55%] Linking CXX executable cvmfs_test_cache
    /usr/bin/ld: CMakeFiles/cvmfs_test_cache.dir/cache_plugin/t_cache_plugin.cc.o: in function `__static_initialization_and_destruction_0()':
    /cvmfs-devel/test/unittests/cache_plugin/t_cache_plugin.cc:77:(.text+0xd2e6): undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
    /usr/bin/ld: /cvmfs-devel/test/unittests/cache_plugin/t_cache_plugin.cc:91:(.text+0xd3d2): undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
    /usr/bin/ld: /cvmfs-devel/test/unittests/cache_plugin/t_cache_plugin.cc:111:(.text+0xd4be): undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
    /usr/bin/ld: /cvmfs-devel/test/unittests/cache_plugin/t_cache_plugin.cc:135:(.text+0xd5aa): undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
    /usr/bin/ld: /cvmfs-devel/test/unittests/cache_plugin/t_cache_plugin.cc:168:(.text+0xd696): undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
    /usr/bin/ld: CMakeFiles/cvmfs_test_cache.dir/cache_plugin/t_cache_plugin.cc.o:/cvmfs-devel/test/unittests/cache_plugin/t_cache_plugin.cc:226: more undefined references to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' follow
    /usr/bin/ld: CMakeFiles/cvmfs_test_cache.dir/cache_plugin/t_cache_plugin.cc.o: in function `testing::internal2::TypeWithoutFormatter<shash::Any, (testing::internal2::TypeKind)2>::PrintValue(shash::Any const&, std::ostream*)':
    /cvmfs-devel/externals_install/include/gtest/gtest-printers.h:140:(.text._ZN7testing9internal220TypeWithoutFormatterIN5shash3AnyELNS0_8TypeKindE2EE10PrintValueERKS3_PSo[_ZN7testing9internal220TypeWithoutFormatterIN5shash3AnyELNS0_8TypeKindE2EE10PrintValueERKS3_PSo]+0x21): undefined reference to `testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*)'
    collect2: error: ld returned 1 exit status
    make[2]: *** [test/unittests/CMakeFiles/cvmfs_test_cache.dir/build.make:243: test/unittests/cvmfs_test_cache] Error 1
    make[1]: *** [CMakeFiles/Makefile2:1265: test/unittests/CMakeFiles/cvmfs_test_cache.dir/all] Error 2
    make: *** [Makefile:146: all] Error 2

    at /cvmfs-devel/externals_build/build_googletest/build:

    $ cmake --version
    cmake version 4.0.1-dirty
    ...
    $ head -n1 ../CMakeLists.txt
    cmake_minimum_required(VERSION 2.6.2)
    $ cmake ..
    CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
     Compatibility with CMake < 3.5 has been removed from CMake.

     Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
     to tell CMake that the project requires at least <min> but has been updated
     to work with policies introduced by <max> or earlier.

     Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.

    -- Configuring incomplete, errors occurred!