ingestsql: acquire_lease(): drop unused bool acquired
Reported by clang-tidy:

error: Value stored to 'acquired' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]