ingestsql: lint: use a var which is already proven non-NULL
Error: /home/runner/work/cvmfs/cvmfs/cvmfs/swissknife_ingestsql.cc:520:34: error: The parameter must not be null [clang-analyzer-cplusplus.StringChecker,-warnings-as-errors]
  520 |     dir_temp = MakeCanonicalPath(getenv("TMPDIR"));
      |                                  ^~~~~~~~~~~~~~~~